Miscellaneous shit
ss220club/Yogstation pull request #25
Opened 2023-06-10 16:45 UTC by Aylong220

# Document the changes in your pull request
Косо-криво портанул свет скайрата
Добавил новые напольные плиты
Плавные створки с приятным звуком со скайрата
Несколько заготовок для маппинга

:cl:  
add: Свет скайрата
tweak: Больше полов
tweak: Планые створки
wip: Заготовки для маппинга
/:cl:

2023-06-10 17:24 UTC, Furrior commented on code/__DEFINES/tools.dm
> +#define TOOL_ACT_SIGNAL_BLOCKING (1<<1)
В модуль

2023-06-10 17:24 UTC, Furrior commented on code/game/machinery/_machinery.dm
> +//SS220 ADDITION END
В модуль

2023-06-10 17:24 UTC, Furrior commented on code/modules/power/lighting.dm
> +
Вот это тоже в модуль можно

2023-06-10 17:24 UTC, Furrior commented on code/modules/power/lighting.dm
> +
В модуль, но тут можно и оставить для предотвращения мизерного падения производительности

2023-06-10 17:24 UTC, Furrior commented on modular_ss220/modules/aesthetics/floors/code/floor.dm
> +	icon_state = "floor_edge"
Путь до иконки не указан? В обычном файле такого икон стейта нет

2023-06-10 17:37 UTC, Aylong220 commented on modular_ss220/modules/aesthetics/floors/code/floor.dm
> +	icon_state = "floor_edge"
Указан в самом начале

2023-06-10 17:39 UTC, Aylong220 commented on modular_ss220/modules/aesthetics/floors/code/floor.dm
> +	icon_state = "floor_edge"
![image](https://github.com/ss220club/Yogstation/assets/69762909/8a066514-dabd-46ee-a4d6-c9b3b0f7b655)

2023-06-17 15:34 UTC, Furrior requested changes

2023-06-17 15:34 UTC, Furrior commented on code/__DEFINES/sound.dm
> +#define CHANNEL_JUKEBOX 1021
Почему бы просто не выделить не по порядку нужный канал вместо перемешивания имеющихся. И почему скайрат едит?

2023-06-17 15:34 UTC, Furrior commented on code/controllers/subsystem/ticker.dm
> +	login_music = pick(
Можно модульо переопределить choose_lobby_music()

2023-06-17 15:34 UTC, Furrior commented on code/game/machinery/dance_machine.dm
> +/* SS220 DELETEION - JUKEBOX - MOVED TO: dance_machine.dm
Можно из .dme файла просто убрать файл

2023-06-17 15:34 UTC, Furrior commented on code/game/sound.dm
> +/client/proc/playtitlemusic(vol = 50)
Раз так делаешь, то модульно лучше прок переопредели

2023-06-17 15:34 UTC, Furrior commented on code/modules/power/lighting.dm
> +/obj/machinery/light/proc/update(trigger = TRUE, instant = FALSE, play_sound = TRUE) //SS220 EDIT
Тут так же

2023-06-17 15:34 UTC, Furrior commented on code/modules/power/lighting.dm
>  /obj/machinery/light/update_atom_colour()
Это модульно можно сделать

2023-06-17 16:28 UTC, Aylong220 commented on code/__DEFINES/sound.dm
> +#define CHANNEL_JUKEBOX 1021
Мы теперь скайран Jokerge. А так, я сначала скопипиздил, а потом заводил

2023-06-17 16:29 UTC, Aylong220 commented on code/controllers/subsystem/ticker.dm
> +	login_music = pick(
Нельзя, пытался, попробую конечно ещё раз, но не работало

2023-06-17 16:29 UTC, Aylong220 commented on code/game/machinery/dance_machine.dm
> +/* SS220 DELETEION - JUKEBOX - MOVED TO: dance_machine.dm
Тогда интересно, почему скайрат так не сделал

2023-06-17 19:59 UTC, Aylong220 commented on code/game/sound.dm
> +/client/proc/playtitlemusic(vol = 50)
![image](https://github.com/ss220club/Yogstation/assets/69762909/993c022f-be8a-4827-8e6f-9c9663f4b6ea)

2023-06-18 02:41 UTC, Furrior commented on code/game/sound.dm
> +/client/proc/playtitlemusic(vol = 50)
Скилл ишью. Убери в своем переопределении /proc

2023-06-18 02:41 UTC, Aylong220 commented on code/game/sound.dm
> +/client/proc/playtitlemusic(vol = 50)
Уже додумался, спасибо xdd

2023-06-20 12:06 UTC, Furrior requested changes
В целом, вроде, норм. Мелкие исправления только.

2023-06-20 12:06 UTC, Furrior commented on yogstation.dme
> -#include "code\game\machinery\dance_machine.dm"
Это закоментить, а не полностью удалять.

2023-06-20 12:06 UTC, Furrior commented on modular_ss220/modules/mapping/code/mapping.dm
> +//Список баров для Кибериады//
Комент на русском плюс странные // в конце?

2023-06-20 12:06 UTC, Furrior commented on modular_ss220/modules/aesthetics/shutters/code/blast_door.dm
> +	icon = 'modular_ss220/modules/aesthetics/shutters/icons/blast_door.dmi'
Как я уже говорил, на всякий, если меняем иконку, то и икон стейт надо

2023-06-20 12:06 UTC, Furrior commented on modular_ss220/modules/aesthetics/shutters/code/shutters.dm
> +	icon = 'modular_ss220/modules/aesthetics/shutters/icons/shutters_window.dmi'
Тут тоже иконстейт

2023-06-20 12:23 UTC, Aylong220 commented on modular_ss220/modules/mapping/code/mapping.dm
> +//Список баров для Кибериады//
Так модули же наши, комфортнее читать на родном языке

2023-06-20 12:25 UTC, Furrior commented on modular_ss220/modules/mapping/code/mapping.dm
> +//Список баров для Кибериады//
Ну тут не то что бы коммент нужен вообще. У тебя список называется потенциальные бары для коробки.

2023-06-20 12:29 UTC, Aylong220 commented on modular_ss220/modules/mapping/code/mapping.dm
> +//Список баров для Кибериады//
В целом это вообще нахуй не надо, ибо пока не планируется выбор баров

2023-06-20 13:06 UTC, Furrior approved these changes

2023-06-20 13:12 UTC, merged